repos:
  - repo: https://github.com/psf/black
    rev: stable
    hooks:
      - id: black
        language_version: python3.7

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.2.3  # Use the ref you want to point at
    hooks:
    - id: check-case-conflict
    - id: check-merge-conflict
    - id: end-of-file-fixer
      exclude: "^\\.idea/*"

    - id: flake8
      additional_dependencies:
      - "flake8-bandit==1.0.2"
      - "flake8-bugbear~=19.3.0"
      - "flake8-string-format~=0.2.3"
      - "pep8-naming~=0.8.2"
      - "pydocstyle<4.0"

    - id: trailing-whitespace
      args: ["--markdown-linebreak-ext=md"]
